### ISSUE TITLE
JanusGraph taking up an insane amount of memory

### ISSUE THREAD

**Issue by firetto** [radiocosmology/padloper#69]
Running the JanusGraph server and loading the DB with 256 chains caused Adam's computer to run out of memory and crash. Lowering Cassandra's `MAX_HEAP_SIZE` to 1G in `cassandra/conf/cassandra-env.sh` made it better behaved. 

Interestingly, for me (Anatoly), running the same script and loading the DB the same way only makes the whole stack use ~2GB total. Note that Adam was using JanusGraph 0.6.1 ("full" release found [here](https://github.com/JanusGraph/janusgraph/releases/tag/v0.6.1)  while I am using JanusGraph v0.6 with the "full" release, found[here](https://github.com/JanusGraph/janusgraph/releases/tag/v0.6.0), on Ubuntu 20.04 LTS.

**Comment by firetto** [comment]
Adam got the DB to be stable by limiting the heap sizes in the following files: 

- `elasticsearch/config/jvm.options`
- `conf/jvm-11.options`

**Comment by ahincks** [comment]
Looked into this more and on a large server the default settings are to use a fair amount of the RAM (presumably because normally JanusGraph is driving a pretty huge database). I put the information from this issue in the README and will now close the issue out.
